# Generated by Django 6.0.2 on 2026-06-24 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_day', models.IntegerField(help_text='Rental priceperday in smallest currency uni')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plugin_hybrid', 'Plug-in Hybrid')], default='petrol', max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('category', models.CharField(choices=[('economy', 'Economy'), ('compact', 'Compact'), ('mid_size', 'Mid_size'), ('full_size', 'Full_size'), ('luxury', 'Luxury'), ('suv', 'Suv'), ('van/minivan', 'Van/Minivan'), ('truck', 'Truck'), ('convertible', 'Convertible'), ('electric', 'Electric')], default='economy', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('is_insured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorited', models.ManyToManyField(blank=True, related_name='favorite_vehicles', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Pickup date')),
                ('end_date', models.DateField(help_text='Return date')),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('number_of_days', models.IntegerField()),
                ('daily_rate', models.IntegerField(help_text='Rate applied at time of booking')),
                ('total_price', models.FloatField()),
                ('driver_age', models.IntegerField(blank=True, null=True)),
                ('has_valid_license', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('mileage_at_pickup', models.IntegerField(blank=True, help_text='Odometer reading', null=True)),
                ('owner_review', models.TextField(blank=True)),
                ('renter_review', models.TextField(blank=True)),
                ('owner_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('renter_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('additional_drivers', models.ManyToManyField(blank=True, help_text='A second driver allowed to handle the property', related_name='additional_drivers', to=settings.AUTH_USER_MODEL)),
                ('primary_driver', models.ForeignKey(help_text='The user who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='property.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/properties')),
                ('is_primary', models.BooleanField(default=False, help_text='Main display image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='properties', to='property.propertyimage'),
        ),
    ]
