# Generated by Django 6.0.2 on 2026-06-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
