# Generated by Django 6.0.2 on 2026-07-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_upated_at_booking_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
    ]
